---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanoscompacts
  - thanosqueries
  - thanosreceives
<<<<<<< HEAD
=======
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosreceives/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosreceives/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosrulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosrulers/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosrulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
>>>>>>> f6da980 (Add Thanos Ruler CRD and deploy logic)
  - thanosservices
  - thanosstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanoscompacts/finalizers
  - thanosqueries/finalizers
  - thanosreceives/finalizers
  - thanosservices/finalizers
  - thanosstores/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanoscompacts/status
  - thanosqueries/status
  - thanosreceives/status
  - thanosservices/status
  - thanosstores/status
  verbs:
  - get
  - patch
  - update
