# permissions for end users to edit thanoscompacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: thanos-operator
    app.kubernetes.io/managed-by: kustomize
  name: thanoscompact-editor-role
rules:
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanoscompacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanoscompacts/status
  verbs:
  - get
