# permissions for end users to edit thanosrulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: thanosruler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/part-of: thanos-operator
    app.kubernetes.io/managed-by: kustomize
  name: thanosruler-editor-role
rules:
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosrulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosrulers/status
  verbs:
  - get
