apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosReceive
metadata:
  name: example-receive
spec:
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  ingestor:
    defaultObjectStorageConfig:
      name: thanos-object-storage
      key: thanos.yaml
    hashrings:
      - name: default
        storageSize: "100Mi"
        tsdbConfig:
          retention: 2h
        tenantMatcherType: exact
        replicas: 1
        externalLabels:
          replica: $(POD_NAME)
  router:
    externalLabels:
      receive: "true"
    replicas: 1
    replicationFactor: 1